name: CI
on:
    pull_request:
    push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
    strategy:
      matrix:
        node-version: ["21.x", "20.x"]