name: CI
on:
    pull_request:
    push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "21.x"
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> "${GITHUB_OUTPUT}"
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: List the state of node modules
        if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: npm list
            