name: CI
on:
    pull_request:
    push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    env:
      MAIN_VERSION: "21.x"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "21.x"
          check-latest: true
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> "${GITHUB_OUTPUT}"
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: List the state of node modules
        if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: npm list
      - name: Prepare coverage report in markdown
        uses: fingerprintjs/action-coverage-report-md@v1.0.6
        id: coverage
        with:
          textReportPath: coverage/coverage.txt
      - name: Add coverage comment to the PR
        uses: marocchino/sticky-pull-request-comment@v2.8.0
        with:
          message: ${{ steps.coverage.outputs.markdownReport }}
      - name: Add coverage report to the job summary
        run: |
          echo "## Code Coverage v${{ matrix.node-version }}" >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.coverage.outputs.markdownReport }}" >> "$GITHUB_STEP_SUMMARY"
