name: Release
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: 21.x
        registry-url: https://npm.pkg.github.com/
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.10.2
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.10.2
      with:
        useConfigFile: true
    - name: Create a new release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create ${{ env.GITVERSION_SEMVER }} --generate-notes
    - name: 'Change NPM version'
      uses: reedyuk/npm-version@1.2.2
      with:
        version: $GITVERSION_SEMVER